### PR TITLE
Halo 3 background fixes.

### PR DESCRIPTION
**Pull request by craftycodie**
2 commits, one for the multiplayer background, one for forge.

### CODE REVIEW

**Comment by Shadowfita** [comment]
Completely over looked that, thanks.

**Comment by craftycodie** [comment]
Thinking about finishing the halo3 css, messed with it a little last night but if I were to finish it would you add the option? [Here's what I did last night](http://i.icap.me/3514404642787380.png).

**Comment by Shadowfita** [comment]
Looks good, have you done all the other options, server browser, settings, etc. That's the main reason we haven't done the other css yet. not enough time to do all the extra stuff.

**Comment by craftycodie** [comment]
Somewhat,  however I wanna mess with a few more designs for the browser before I start work on anything final.

**Pull request merged**
